services:
  gitlab:
    image: gitlab/gitlab-ce:17.4.6-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://150.95.83.13'
        gitlab_rails['initial_root_password'] = File.read('/run/secrets/gitlab_root_password').strip
        gitlab_rails['initial_root_email'] = File.read('/run/secrets/gitlab_root_email').strip
    ports:
      - '8090:80'
      - '8443:443'
      - '2022:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    secrets:
      - gitlab_root_password
      - gitlab_root_email

secrets:
  gitlab_root_password:
    file: ./secrets/gitlab_root_password
  gitlab_root_email:
    file: ./secrets/gitlab_root_email

